version: "3.5"

services:
  db:
    build:
      context: database
    volumes:
      # 永続化するときにマウントするdir
      - ./postgres:/var/lib/postgresql
      # 初期データを投入するSQLが格納されているdir
      - ./postgres-init:/docker-entrypoint-initdb.d
    expose:
      - '5432'
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: 'always'
    networks:
      - db-net




networks:
  db-net:
    driver: bridge